// AUTO-GENERATED by gen-assets.ts — full string literals
// so tools/build.ts bakes every image, plus per-map geometry.

export const MAP_CANVAS_PX = 512;

export const MAP_GROUND: Record<string, string> = {
  "hub": "assets/map-hub-ground.png",
  "farm": "assets/map-farm-ground.png",
  "mine": "assets/map-mine-ground.png",
  "pine": "assets/map-pine-ground.png",
  "light": "assets/map-light-ground.png",
};

export const MAP_UPPER: Record<string, string> = {
  "hub": "assets/map-hub-upper.png",
  "farm": "assets/map-farm-upper.png",
  "mine": "assets/map-mine-upper.png",
  "pine": "assets/map-pine-upper.png",
  "light": "assets/map-light-upper.png",
};

export const MAP_WORLD: Record<string, { w: number; h: number }> = {
  "hub": { w: 384, h: 240 },
  "farm": { w: 352, h: 224 },
  "mine": { w: 256, h: 192 },
  "pine": { w: 288, h: 192 },
  "light": { w: 256, h: 224 },
};

export const MAP_ORDER: readonly string[] = ["hub","farm","mine","pine","light"];

export const NPC_SRC: Record<string, string> = {
  "postmaster": "assets/npc/postmaster.png",
  "shopkeeper": "assets/npc/shopkeeper.png",
  "clerk": "assets/npc/clerk.png",
  "farmer": "assets/npc/farmer.png",
  "miner": "assets/npc/miner.png",
  "hermit": "assets/npc/hermit.png",
  "keeper": "assets/npc/keeper.png",
  "wanderer": "assets/npc/wanderer.png",
  "sheep": "assets/npc/sheep.png",
  "chest-closed": "assets/npc/chest-closed.png",
  "chest-open": "assets/npc/chest-open.png",
  "sign": "assets/npc/sign.png",
  "mailbox": "assets/npc/mailbox.png",
  "parcel": "assets/npc/parcel.png",
  "hay": "assets/npc/hay.png",
  "mushrooms": "assets/npc/mushrooms.png",
  "fire-off": "assets/npc/fire-off.png",
  "lamp-off": "assets/npc/lamp-off.png",
};

export const PLAYER_IDLE: string[] = [
  "assets/player-dir0.png",
  "assets/player-dir1.png",
  "assets/player-dir2.png",
  "assets/player-dir3.png",
];

export const PLAYER_WALK_L: string[] = [
  "assets/player-pose0-l.png",
  "assets/player-pose1-l.png",
  "assets/player-pose2-l.png",
  "assets/player-pose3-l.png",
];

export const PLAYER_WALK_R: string[] = [
  "assets/player-pose0-r.png",
  "assets/player-pose1-r.png",
  "assets/player-pose2-r.png",
  "assets/player-pose3-r.png",
];

// Speaker portraits for the dialog box, keyed by the name a line starts
// with ("POSTMASTER: ...").
export const FACE_SRC: Record<string, string> = {
  "POSTMASTER": "assets/face/postmaster.png",
  "CLERK": "assets/face/clerk.png",
  "FARMER": "assets/face/farmer.png",
  "MINER": "assets/face/miner.png",
  "HERMIT": "assets/face/hermit.png",
  "KEEPER": "assets/face/keeper.png",
};

// Vblank auto-play atlases (sprites.json); the core cycles the frames,
// guest JS never touches them per frame. src key -> frame step.
export const ANIM_ATLASES: Record<string, { src: string; frames: number; step: number }> = {
  "water": { src: "assets/anim/water.png", frames: 2, step: 24 },
  "fire": { src: "assets/anim/fire.png", frames: 4, step: 8 },
  "lamp": { src: "assets/anim/lamp.png", frames: 2, step: 22 },
  "beacon": { src: "assets/anim/beacon.png", frames: 2, step: 10 },
};
